Repository freezingsaddles/freezing-compose, pull requests merged in 2025-01, with the labels that each got.

#52 fix deploy
  .github/workflows/deploy.yml
  .gitignore
Labels: bug

#54 Prune old docker images
  bin/docker-images-prune.sh
Labels: enhancement, infrastructure

#55 Fix default branch name to main
  .github/workflows/deploy.yml
Labels: enhancement

#56 Fix fine point in deploy
  .github/workflows/deploy.yml
Labels: bug

#59 rename /data to /cache
  docker-compose.yml
  web-cache/.gitkeep
Labels: bug

#61 use tmpfs for cache
  docker-compose.yml
Labels: bug
